### ISSUE TITLE
'unistd.h' not found - Compilation under Windows + VisualStudio fails

### ISSUE THREAD

**Issue by chfw** [amol-/dukpy#20]
Hello, 

I came to your lib via javascripthon. Do you have any plan to support windows build? 

Thanks

Here are the errors:

```
    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DDUK_OPT_DEEP_C_STACK=1 -DDUK_OPT_NONSTD_REGEXP_DOLLAR_ESCAPE=1 -DDUK_OPT_OCTAL_SUPPORT=1 -I.\src\duktape -IC:\Python35-x64\include -IC:\Python35-x64\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /Tcsrc\duktape\duktape.c /Fobuild\temp.win-amd64-3.5\Release\src\duktape\duktape.obj
336    duktape.c
337    C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DDUK_OPT_DEEP_C_STACK=1 -DDUK_OPT_NONSTD_REGEXP_DOLLAR_ESCAPE=1 -DDUK_OPT_OCTAL_SUPPORT=1 -I.\src\duktape -IC:\Python35-x64\include -IC:\Python35-x64\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\winrt" /Tcsrc\_support.c /Fobuild\temp.win-amd64-3.5\Release\src\_support.obj
338    _support.c
339    src\_support.c(1): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory
340    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
341    
342    ----------------------------------------
343Command "C:\Python35-x64\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\pip-build-i9t2zpp9\\dukpy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\appveyor\AppData\Local\Temp\1\pip-46n0b6pn-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\appveyor\AppData\Local\Temp\1\pip-build-i9t2zpp9\dukpy\
```

**Comment by amol-** [comment]
Hi,

I have to admit that I don't recall anymore the reason why `unistd.h` was used, the codebase changed during the years so it might actually be unused right now. Removing it seems to build just fine.

I don't have a windows system available, so it would greatly help if you could clone the repository on your system, remove the `#include <unistd.h>` line from `src/_support.c` and `src/pyduktape.c`  and let me know if you are then able to install the package. Running `python setup.py bdist` should build the binary without the need to actually install it.

**Comment by webknjaz** [comment]
AFAIR this lib provides POSIX syscalls capabilities. So it could probably be wrapped with `#ifdef`s. Otherwise cygwin/mingw might be needed.

P.S. I can look at implementing building/publishing wheels using Appveyor CI.
P.P.S. It is a good idea to actually publish wheels, so that users would not need to compile anything on target machines.

**Comment by amol-** [comment]
I know that `unistd.h` is unix related, but I don't thing we actually use anymore anything provided by it. That's why I was suggesting to just try removing it and see if it builds.

Regarding wheels I'm totally for them, just didn't have time to build them so far.
For linux they can be automated through travis, for windows we can try appveyor as they provide a free plan for OSS projects.

**Comment by amol-** [comment]
I set up an appveyor configuration for dukpy. As expected `unistd.h` wasn't required, but there were other compatibility issues with VisualStudio Compiler that required to migrate codebase from C99 to C89 and some encoding incompatibilities due to Windows not using UTF8.

DukPY now mostly builds and passes tests on Windows for both Py27 and Py3: https://ci.appveyor.com/project/amol-/dukpy/build/1.0.11

There are some problems with x64 builds for Py3 that I didn't have time to investigate yet, I'll try to address them by the weekend and roll out a new release once I also added 3.5 and 3.6 wheels builds.

**Comment by webknjaz** [comment]
@amol- ping me after it's merged: I'll help you to configure publishing windows wheels from AppVeyor CI as well.

**Comment by amol-** [comment]
I was able to get `appveyor` pass on all python versions and build the relevant wheels: https://ci.appveyor.com/project/amol-/dukpy/build/1.0.17

**Comment by amol-** [comment]
Will have to add more Python 3.5 and 3.6 and then I think it's done.

**Comment by webknjaz** [comment]
@amol- merge in #21 to your branch and commit creds, then you should be ready to go

**Comment by webknjaz** [comment]
Ref #22

**Comment by amol-** [comment]
DukPy 0.2.0 was released with prebuilt wheels for windows.
